In [ ]:
def EMISSAO_BUT(ta_but,te_but):

In [149]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np

In [155]:
df = pd.read_csv(r"C:\Users\marcos perrude\Documents\LCQAR\dados\vendas-anuais-de-glp-por-municipio.csv",encoding ='latin1')
df['TOTAL'] = df['P13'] + df['OUTROS']
df.rename(columns={'ï»¿ANO': 'ANO'}, inplace = True)
df

,ANO,GRANDE REGIAO,UF,PRODUTO,CODIGO IBGE,MUNICIPIO,P13,OUTROS,TOTAL
0,1992,REGIÃO SUDESTE,RJ,GLP,3303500,NOVA IGUACU,32483584,1483879,33967463
1,1992,REGIÃO SUDESTE,RJ,GLP,3304558,RIO DE JANEIRO,103821744,14441443,118263187
2,1992,REGIÃO SUDESTE,RJ,GLP,3304906,SAO GONCALO,19136742,1489934,20626676
3,1992,REGIÃO NORDESTE,PI,GLP,2201909,BOM JESUS,564007,0,564007
4,1992,REGIÃO NORDESTE,PI,GLP,2202301,CANTO DO BURITI,260858,0,260858
...,...,...,...,...,...,...,...,...,...
132745,2022,REGIÃO NORTE,TO,GLP,1721000,PALMAS,9779753,1555379,11335132
132746,2022,REGIÃO NORTE,TO,GLP,1721109,TOCANTINIA,80977,0,80977
132747,2022,REGIÃO NORTE,TO,GLP,1721208,TOCANTINOPOLIS,172429,25935,198364
132748,2022,REGIÃO NORTE,TO,GLP,1721307,TUPIRATINS,6175,0,6175
132749,2022,REGIÃO NORTE,TO,GLP,1722107,XAMBIOA,0,7507,7507

In [156]:
# Converter kg para m³, e aplicar o fator de converte de Lb/galao -> kg/m³
df['TOTAL'] = ((df['TOTAL'] / 2.3)* 0.12)
df

,ANO,GRANDE REGIAO,UF,PRODUTO,CODIGO IBGE,MUNICIPIO,P13,OUTROS,TOTAL
0,1992,REGIÃO SUDESTE,RJ,GLP,3303500,NOVA IGUACU,32483584,1483879,1.772215e+06
1,1992,REGIÃO SUDESTE,RJ,GLP,3304558,RIO DE JANEIRO,103821744,14441443,6.170253e+06
2,1992,REGIÃO SUDESTE,RJ,GLP,3304906,SAO GONCALO,19136742,1489934,1.076174e+06
3,1992,REGIÃO NORDESTE,PI,GLP,2201909,BOM JESUS,564007,0,2.942645e+04
4,1992,REGIÃO NORDESTE,PI,GLP,2202301,CANTO DO BURITI,260858,0,1.360998e+04
...,...,...,...,...,...,...,...,...,...
132745,2022,REGIÃO NORTE,TO,GLP,1721000,PALMAS,9779753,1555379,5.913982e+05
132746,2022,REGIÃO NORTE,TO,GLP,1721109,TOCANTINIA,80977,0,4.224887e+03
132747,2022,REGIÃO NORTE,TO,GLP,1721208,TOCANTINOPOLIS,172429,25935,1.034943e+04
132748,2022,REGIÃO NORTE,TO,GLP,1721307,TUPIRATINS,6175,0,3.221739e+02
132749,2022,REGIÃO NORTE,TO,GLP,1722107,XAMBIOA,0,7507,3.916696e+02

In [160]:
def Taxa_butano(taxa_butano):
    #Definir os fatores de emissao (AP42) PARA butano
    teb = {
        'PMtotal': [0.2],
        'SO2' : [0.09],
        'NOx' : [15],
        'N20' : [0.9],
        'CO2' : [14.300],
        'CO' : [8.4],
        'CH4' : [0.2],
    }
    teb = pd.DataFrame(teb)
    
    #obter as taxas de emissoes para butano
    resultados = df['TOTAL'].values[:, np.newaxis] * teb.values
    Taxa_butano = pd.DataFrame(resultados, columns=[f'TOTAL_{col}' for col in teb.columns])
    return Taxa_butano

,TOTAL_PMtotal,TOTAL_SO2,TOTAL_NOx,TOTAL_N20,TOTAL_CO2,TOTAL_CO,TOTAL_CH4
0,3.544431e+05,159499.391478,2.658323e+07,1.594994e+06,2.534268e+07,1.488661e+07,3.544431e+05
1,1.234051e+06,555322.791130,9.255380e+07,5.553228e+06,8.823462e+07,5.183013e+07,1.234051e+06
2,2.152349e+05,96855.696000,1.614262e+07,9.685570e+05,1.538929e+07,9.039865e+06,2.152349e+05
3,5.885290e+03,2648.380696,4.413968e+05,2.648381e+04,4.207983e+05,2.471822e+05,5.885290e+03
4,2.721997e+03,1224.898435,2.041497e+05,1.224898e+04,1.946228e+05,1.143239e+05,2.721997e+03
...,...,...,...,...,...,...,...
132745,1.182796e+05,53225.837217,8.870973e+06,5.322584e+05,8.456994e+06,4.967745e+06,1.182796e+05
132746,8.449774e+02,380.239826,6.337330e+04,3.802398e+03,6.041588e+04,3.548905e+04,8.449774e+02
132747,2.069885e+03,931.448348,1.552414e+05,9.314483e+03,1.479968e+05,8.693518e+04,2.069885e+03
132748,6.443478e+01,28.995652,4.832609e+03,2.899565e+02,4.607087e+03,2.706261e+03,6.443478e+01
132749,7.833391e+01,35.250261,5.875043e+03,3.525026e+02,5.600875e+03,3.290024e+03,7.833391e+01

In [101]:
df = pd.concat([df, result_df],axis = 1)

In [102]:
df

,ANO,GRANDE REGIAO,UF,PRODUTO,CODIGO IBGE,MUNICIPIO,P13,OUTROS,TOTAL,TOTAL_PMtotal,TOTAL_SO2,TOTAL_NOx,TOTAL_N20,TOTAL_CO2,TOTAL_CO,TOTAL_CH4
0,1992,REGIÃO SUDESTE,RJ,GLP,3303500,NOVA IGUACU,32483584,1483879,33967463,6793492.6,3057071.67,5.095119e+08,30570716.7,4.857347e+08,285326689.2,6793492.6
1,1992,REGIÃO SUDESTE,RJ,GLP,3304558,RIO DE JANEIRO,103821744,14441443,118263187,23652637.4,10643686.83,1.773948e+09,106436868.3,1.691164e+09,993410770.8,23652637.4
2,1992,REGIÃO SUDESTE,RJ,GLP,3304906,SAO GONCALO,19136742,1489934,20626676,4125335.2,1856400.84,3.094001e+08,18564008.4,2.949615e+08,173264078.4,4125335.2
3,1992,REGIÃO NORDESTE,PI,GLP,2201909,BOM JESUS,564007,0,564007,112801.4,50760.63,8.460105e+06,507606.3,8.065300e+06,4737658.8,112801.4
4,1992,REGIÃO NORDESTE,PI,GLP,2202301,CANTO DO BURITI,260858,0,260858,52171.6,23477.22,3.912870e+06,234772.2,3.730269e+06,2191207.2,52171.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132745,2022,REGIÃO NORTE,TO,GLP,1721000,PALMAS,9779753,1555379,11335132,2267026.4,1020161.88,1.700270e+08,10201618.8,1.620924e+08,95215108.8,2267026.4
132746,2022,REGIÃO NORTE,TO,GLP,1721109,TOCANTINIA,80977,0,80977,16195.4,7287.93,1.214655e+06,72879.3,1.157971e+06,680206.8,16195.4
132747,2022,REGIÃO NORTE,TO,GLP,1721208,TOCANTINOPOLIS,172429,25935,198364,39672.8,17852.76,2.975460e+06,178527.6,2.836605e+06,1666257.6,39672.8
132748,2022,REGIÃO NORTE,TO,GLP,1721307,TUPIRATINS,6175,0,6175,1235.0,555.75,9.262500e+04,5557.5,8.830250e+04,51870.0,1235.0
132749,2022,REGIÃO NORTE,TO,GLP,1722107,XAMBIOA,0,7507,7507,1501.4,675.63,1.126050e+05,6756.3,1.073501e+05,63058.8,1501.4

In [88]:
df = pd.concat([df, result_df],axis = 1)
df.drop(['P13','OUTROS','PRODUTO'],axis = 1)

,ANO,GRANDE REGIAO,UF,CODIGO IBGE,MUNICIPIO,TOTAL,TOTAL_PMtotal,TOTAL_SO2,TOTAL_NOx,TOTAL_N20,TOTAL_CO2,TOTAL_CO,TOTAL_CH4
0,1992,REGIÃO SUDESTE,RJ,3303500,NOVA IGUACU,33967463,6793492.6,3057071.67,5.095119e+08,30570716.7,4.857347e+08,285326689.2,6793492.6
1,1992,REGIÃO SUDESTE,RJ,3304558,RIO DE JANEIRO,118263187,23652637.4,10643686.83,1.773948e+09,106436868.3,1.691164e+09,993410770.8,23652637.4
2,1992,REGIÃO SUDESTE,RJ,3304906,SAO GONCALO,20626676,4125335.2,1856400.84,3.094001e+08,18564008.4,2.949615e+08,173264078.4,4125335.2
3,1992,REGIÃO NORDESTE,PI,2201909,BOM JESUS,564007,112801.4,50760.63,8.460105e+06,507606.3,8.065300e+06,4737658.8,112801.4
4,1992,REGIÃO NORDESTE,PI,2202301,CANTO DO BURITI,260858,52171.6,23477.22,3.912870e+06,234772.2,3.730269e+06,2191207.2,52171.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132745,2022,REGIÃO NORTE,TO,1721000,PALMAS,11335132,2267026.4,1020161.88,1.700270e+08,10201618.8,1.620924e+08,95215108.8,2267026.4
132746,2022,REGIÃO NORTE,TO,1721109,TOCANTINIA,80977,16195.4,7287.93,1.214655e+06,72879.3,1.157971e+06,680206.8,16195.4
132747,2022,REGIÃO NORTE,TO,1721208,TOCANTINOPOLIS,198364,39672.8,17852.76,2.975460e+06,178527.6,2.836605e+06,1666257.6,39672.8
132748,2022,REGIÃO NORTE,TO,1721307,TUPIRATINS,6175,1235.0,555.75,9.262500e+04,5557.5,8.830250e+04,51870.0,1235.0
132749,2022,REGIÃO NORTE,TO,1722107,XAMBIOA,7507,1501.4,675.63,1.126050e+05,6756.3,1.073501e+05,63058.8,1501.4

In [ ]:
# Carrega o shapefile dos municípios brasileiros (ajuste o caminho para onde o arquivo shapefile está salvo)
brasil_municipios = gpd.read_file(r"C:\Users\marcos perrude\Documents\LCQAR\dados\BR_Municipios_2022.shp")

# Verifique as primeiras linhas do GeoDataFrame
print(brasil_municipios.head())

In [ ]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# Carrega o shapefile dos municípios brasileiros
brasil_municipios = gpd.read_file(r"C:\Users\marcos perrude\Downloads\BR_Municipios_2022\BR_Municipios_2022.dbf")

# Converte a coluna 'CD_MUN' e 'CODIGO IBGE' para string
brasil_municipios['CD_MUN'] = brasil_municipios['CD_MUN'].astype(str)
df['CODIGO IBGE'] = df['CODIGO IBGE'].astype(str)

# Faz o merge entre o shapefile e os dados do dataframe 'df'
mapa_merged = brasil_municipios.merge(df, left_on='CD_MUN', right_on='CODIGO IBGE', how='left')

# Configura uma escala logarítmica para melhor visualização da concentração
fig, ax = plt.subplots(1, 1, figsize=(15, 15))

# Normaliza os valores para a escala logarítmica (evita log(0) adicionando um pequeno valor)
norm = mcolors.LogNorm(vmin=mapa_merged['TOTAL'].min() + 1, vmax=mapa_merged['TOTAL'].max())

# Plota o mapa com uma escala de cor contínua para 'TOTAL'
mapa_merged.plot(column='TOTAL', ax=ax, legend=True, cmap='OrRd', edgecolor='black', norm=norm)

# Título e exibição do mapa
plt.title('Mapa de Concentração do TOTAL por Município do Brasil (Escala Logarítmica)')
plt.show()

RuntimeError: python error has been set

In [52]:
df['datetime'] = pd.to_datetime(df['ANO'].astype(str) + '-01-01', format='%Y-%m-%d')

In [53]:
df

,ANO,GRANDE REGIAO,UF,PRODUTO,CODIGO IBGE,MUNICIPIO,P13,OUTROS,TOTAL,datetime
0,1992,REGIÃO SUDESTE,RJ,GLP,3303500,NOVA IGUACU,32483584,1483879,33967463,1992-01-01
1,1992,REGIÃO SUDESTE,RJ,GLP,3304558,RIO DE JANEIRO,103821744,14441443,118263187,1992-01-01
2,1992,REGIÃO SUDESTE,RJ,GLP,3304906,SAO GONCALO,19136742,1489934,20626676,1992-01-01
3,1992,REGIÃO NORDESTE,PI,GLP,2201909,BOM JESUS,564007,0,564007,1992-01-01
4,1992,REGIÃO NORDESTE,PI,GLP,2202301,CANTO DO BURITI,260858,0,260858,1992-01-01
...,...,...,...,...,...,...,...,...,...,...
132745,2022,REGIÃO NORTE,TO,GLP,1721000,PALMAS,9779753,1555379,11335132,2022-01-01
132746,2022,REGIÃO NORTE,TO,GLP,1721109,TOCANTINIA,80977,0,80977,2022-01-01
132747,2022,REGIÃO NORTE,TO,GLP,1721208,TOCANTINOPOLIS,172429,25935,198364,2022-01-01
132748,2022,REGIÃO NORTE,TO,GLP,1721307,TUPIRATINS,6175,0,6175,2022-01-01
132749,2022,REGIÃO NORTE,TO,GLP,1722107,XAMBIOA,0,7507,7507,2022-01-01

In [36]:
df.query('`Mercado Destinatário` == "CONSUMIDOR FINAL"')

,Ano,Mês,Agente Regulado,Código do Produto,Nome do Produto,Região Origem,UF Origem,Região Destinatário,UF Destino,Mercado Destinatário,Código de Embalagem GLP,Quantidade(mil ton)
0,2021,1,AMAZONGAS DISTRIB DE GAS LIQUEF DE PETROLEO LTDA,210203001.0,GLP,N,AC,N,AC,CONSUMIDOR FINAL,P 7,651
1,2021,1,AMAZONGAS DISTRIB DE GAS LIQUEF DE PETROLEO LTDA,210203001.0,GLP,N,AC,N,AC,CONSUMIDOR FINAL,P 13,11648
2,2021,1,AMAZONGAS DISTRIB DE GAS LIQUEF DE PETROLEO LTDA,210203001.0,GLP,N,AC,N,AC,CONSUMIDOR FINAL,P 20,4580
3,2021,1,AMAZONGAS DISTRIB DE GAS LIQUEF DE PETROLEO LTDA,210203001.0,GLP,N,AC,N,AC,CONSUMIDOR FINAL,P 45,2475
4,2021,1,AMAZONGAS DISTRIB DE GAS LIQUEF DE PETROLEO LTDA,210203001.0,GLP,N,AC,N,AC,CONSUMIDOR FINAL,A Granel,40254
...,...,...,...,...,...,...,...,...,...,...,...,...
296482,2007,12,SUPERGASBRAS ENERGIA LTDA,210203001.0,GLP,S,PR,N,TO,CONSUMIDOR FINAL,P 20,3400
296483,2007,12,SUPERGASBRAS ENERGIA LTDA,210203001.0,GLP,N,TO,N,TO,CONSUMIDOR FINAL,P 45,4950
296484,2007,12,SUPERGASBRAS ENERGIA LTDA,210203001.0,GLP,S,PR,N,TO,CONSUMIDOR FINAL,P 45,1620
296485,2007,12,SUPERGASBRAS ENERGIA LTDA,210203001.0,GLP,N,TO,N,TO,CONSUMIDOR FINAL,P 90,540
296486,2007,12,SUPERGASBRAS ENERGIA LTDA,210203001.0,GLP,S,PR,N,TO,CONSUMIDOR FINAL,A Granel,123

In [37]:
df.dtypes

Ano                          int64
Mês                          int64
Agente Regulado             object
Código do Produto          float64
Nome do Produto             object
Região Origem               object
UF Origem                   object
Região Destinatário         object
UF Destino                  object
Mercado Destinatário        object
Código de Embalagem GLP     object
Quantidade(mil ton)         object
dtype: object

In [38]:
df['Quantidade(mil ton)'] = df['Quantidade(mil ton)'].astype('int')

ValueError: invalid literal for int() with base 10: ' TRANSPORTE E DISTRIBUIÇÃO DE GLP RIO CLARO LTDA.;210203001;GLP;SE;SP;SE;SP;CONSUMIDOR FINAL;A Granel;0'

In [19]:
df.groupby(['UF Origem'])[['Quantidade(mil ton)']].sum()

TypeError: can only concatenate str (not "int") to str